extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
env:
  node: true
  mocha: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
"ignorePatterns":
  - "dist/"